import os
import base64
from email.message import EmailMessage
from dotenv import load_dotenv
from googleapiclient.discovery import build

from src.mcp.auth import get_google_credentials


load_dotenv()


def format_body(payload: dict) -> str:
    """
    Format payload into the email body text.
    """
    pulse = payload["weekly_pulse"]
    top_themes = " | ".join(pulse["top_themes"])
    note = pulse["note"]
    actions = "\n".join(f"{i+1}. {a}" for i, a in enumerate(pulse["actions"]))
    quotes = "\n".join(f"- \"{q['text']}\"" for q in pulse["quotes"])
    
    fee_scenario = payload["fee_scenario"]
    bullets = "\n".join(f"• {b}" for b in payload["explanation_bullets"])
    sources = "\n".join(f"- {s['label']}: {s['url']}" for s in payload["source_links"])
    
    return f"""Hi team,

== WEEKLY PRODUCT PULSE — {payload["date"]} ==

{note}

Top themes: {top_themes}

Action ideas:
{actions}

User quotes:
{quotes}


== FEE EXPLAINER — {fee_scenario} ==

{bullets}

Official sources:
{sources}

Last checked: {payload["last_checked"]}

---
Generated by INDmoney AI Workflow. This is a draft — review before sending."""


def format_html_body(payload: dict) -> str:
    """
    Format payload into structured and visually hierarchical HTML body.
    """
    pulse = payload["weekly_pulse"]
    top_themes = " | ".join(pulse["top_themes"])
    note = payload["weekly_pulse"]["note"].replace("\n", "<br>")
    actions = "\n".join(f"<li>{a}</li>" for a in pulse["actions"])
    quotes = "\n".join(f"<li><em>\"{q['text']}\"</em></li>" for q in pulse["quotes"])
    
    fee_scenario = payload["fee_scenario"]
    bullets = "\n".join(f"<li>{b}</li>" for b in payload["explanation_bullets"])
    sources = "\n".join(f"<li><a href=\"{s['url']}\" style=\"color: #4e73df; text-decoration: none;\">{s['label']}</a></li>" for s in payload["source_links"])
    
    return f"""\
<html>
  <head>
    <style>
      body {{ font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; line-height: 1.6; color: #333; }}
      .container {{ max-width: 600px; margin: 0 auto; background: #fff; padding: 20px; }}
      h2 {{ color: #2c3e50; border-bottom: 2px solid #eee; padding-bottom: 8px; margin-top: 30px; font-size: 18px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; }}
      h3 {{ color: #34495e; margin-top: 20px; font-size: 15px; font-weight: 600; display: flex; align-items: center; gap: 8px; }}
      .note {{ background: #f8f9fc; padding: 15px 20px; border-left: 4px solid #4e73df; margin: 20px 0; border-radius: 0 4px 4px 0; font-size: 14.5px; }}
      .themes {{ font-weight: 600; color: #e74a3b; padding: 2px 8px; background: #fdf5f4; border-radius: 4px; font-size: 14px; display: inline-block; margin-left: 8px; }}
      ul {{ margin-top: 10px; padding-left: 20px; }}
      li {{ margin-bottom: 8px; font-size: 14.5px; }}
      .footer {{ margin-top: 40px; padding-top: 20px; border-top: 1px solid #eee; font-size: 12px; color: #858796; text-align: center; }}
      .emoji {{ font-size: 16px; margin-right: 6px; }}
    </style>
  </head>
  <body>
    <div class="container">
      <p style="font-size: 15px;">Hi team,</p>
      
      <h2><span class="emoji">📊</span> WEEKLY PRODUCT PULSE — {payload["date"]}</h2>
      
      <div class="note">
        {note}
      </div>
      
      <div style="display: flex; align-items: center; margin: 20px 0;">
        <strong>Top themes:</strong> <span class="themes">{top_themes}</span>
      </div>
      
      <h3><span class="emoji">🚀</span> Action Ideas</h3>
      <ul>
{actions}
      </ul>
      
      <h3><span class="emoji">💬</span> User Quotes</h3>
      <ul>
{quotes}
      </ul>
      
      <h2><span class="emoji">💡</span> FEE EXPLAINER — {fee_scenario}</h2>
      <ul>
{bullets}
      </ul>
      
      <h3><span class="emoji">📚</span> Official Sources</h3>
      <ul>
{sources}
      </ul>
      
      <div class="footer">
        <p style="margin-bottom: 4px;">Last checked: {payload["last_checked"]}</p>
        <p style="margin-top: 0;"><em>Generated by INDmoney AI Workflow. This is a draft — review before sending.</em></p>
      </div>
    </div>
  </body>
</html>
"""


def create_draft(payload: dict) -> bool:
    """
    Create a Gmail draft using Google official APIs directly. 
    Matches HC-8 (create_draft only, no auto-send).
    Returns True on success, False on failure.
    """
    creds = get_google_credentials()
    recipient = os.getenv("DRAFT_RECIPIENT")

    if not recipient:
        print("Gmail draft failed: Missing DRAFT_RECIPIENT in environment.")
        return False
    if not creds:
        print("Gmail draft failed: Invalid or missing GOOGLE_CREDENTIALS_BASE64.")
        return False

    subject = f"Weekly Pulse + Fee Explainer — {payload['date']}"
    text_body = format_body(payload)
    html_body = format_html_body(payload)

    # Compile proper MIME email required for drafting
    message = EmailMessage()
    message["To"] = recipient
    message["Subject"] = subject
    message.set_content(text_body)
    message.add_alternative(html_body, subtype='html')

    # Base64url encoded representation of the raw MIME standard
    encoded_message = base64.urlsafe_b64encode(message.as_bytes()).decode()

    create_message = {
        "message": {
            "raw": encoded_message
        }
    }

    try:
        # Build Standard Gmail V1 endpoint
        service = build("gmail", "v1", credentials=creds, cache_discovery=False)
        
        # We explicitly enforce drafts().create() instead of messages.send! (HC-8)
        service.users().drafts().create(
            userId="me", 
            body=create_message
        ).execute()

        print("Gmail API draft created successfully. Check your Drafts folder.")
        return True
    
    except Exception as e:
        print(f"Gmail drafting API failed: {e}")
        return False
